import Head from "next/head";
import { AnimatePresence, AnimateSharedLayout } from "framer-motion";
import { NextComponentType } from "next";
import type { AppContext, AppInitialProps, AppProps } from "next/app";
import { withPrefix } from "../../with-prefix";

import "../styles/font.css";
import "../styles/globals.css";
import "../styles/reset.css";

const CustomApp: NextComponentType<AppContext, AppInitialProps, AppProps> = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests" />
        <link rel="icon" href={withPrefix("/favicon.ico")} />
      </Head>
      <AnimatePresence exitBeforeEnter initial={false}>
        <AnimateSharedLayout>
          <Component {...pageProps} />
        </AnimateSharedLayout>
      </AnimatePresence>
      <footer
        css={{
          position: "fixed",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          height: 50,
          bottom: 0,
          width: "100%",
          borderTop: "1px solid #eaeaea",
          backdropFilter: "blur(8px)",
          boxShadow: "0px 10px 15px 10px rgb(0 0 0 / 5%)",
          backgroundColor: "rgb(255 255 255 / 35%)",
        }}
      >
        <a
          href="https://github.com/lauramarinab"
          target="_blank"
          rel="noopener noreferrer"
          css={{ fontSize: "0.8rem" }}
        >
          powered by lauramarinab{" "}
          <span role="img" aria-label="hearth">
            ❤️
          </span>
        </a>
      </footer>
    </>
  );
};

export default CustomApp;
