import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { withPrefix } from "../../with-prefix";
import { Main } from "../components/Main";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={withPrefix("/favicon.ico")} />
      </Head>

      <Main>
        <h1 style={{ fontSize: "3rem", display: "flex", alignItems: "center", gap: 24 }}>
          Weather with blob
          <span>
            <img src={withPrefix("/images/blob-cookie.png")} alt="blob cookie" width={50} height={50} />
          </span>
        </h1>

        <Link href="/today" passHref>
          <a>Che tempo farà domani?</a>
        </Link>
      </Main>

      <footer
        style={{
          position: "fixed",
          bottom: 0,
          width: "100%",
          padding: "0.8rem 0",
          borderTop: "1px solid #eaeaea",
          textAlign: "center",
        }}
      >
        <a
          href="https://github.com/lauramarinab"
          target="_blank"
          rel="noopener noreferrer"
          style={{ fontSize: "0.8rem" }}
        >
          powered by lauramarinab{" "}
          <span role="img" aria-label="hearth">
            ❤️
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
